### ISSUE TITLE
Invalid year XX in readclimate()

### ISSUE THREAD

**Issue by zhengjiji456** [PIK-LPJmL/LPJmL#18]
Hi, thanks for the previous guidance for running the model. 
I prepared a simple simulation at the global scale (720 360) with the CRU climate data and soil data gswp3_hwsd downloaded from ISIMIP. 
When I started the model from the restart file "restart_1840_nv_stdfire.lpj", the simulation started successfully but failed in the year 2004. The error message showed "Invalid year 2004 in readclimate()". In addition, only 1660 cells processed, and many error messages showed "negative evaporation". 
![捕获](https://user-images.githubusercontent.com/21077143/153979438-510122cf-8819-4921-ae36-89e4853634ab.JPG)

**Comment by sostberg** [comment]
Have a look in readclimate() where this error message was triggered. It suggests that you were trying to read data for a year that's not covered by your input file.

In general, you should always check the code when you see an error message in the print out. If the error message itself is not clear seeing the context in which it was triggered can often help you to determine the cause of the error. 

If you say that you have prepared global input datasets LPJmL should not only simulate 1660 grid cells. CRU data cover 67420 land grid cells.

Based on the multiple lines of "ERROR212" your grid file is incorrect since there should be no latitude coordinates above 90°N, nor should there be longitude coordinates above 180°E

And just a note on the gswp3_hwsd soil file from ISIMIP: This uses different soil codes than LPJmL. You will have to find out which soil texture classes the codes in the ISIMIP file correspond to and then map this to the soil codes used by LPJmL. You can find the sequence of soil texture classes used by LPJmL in par/soil.par (starting with 1 for clay).

**Comment by zhengjiji456** [comment]
Hi, thanks for your suggestions.
I used the function "cru2clm" to convert all the CRU data files into LPJ climate data files as inputs. There is no missing year (e.g. 2004) or data in the original nc files. 
I used the function "cdf2soil" to convert the gswp3_hwsd soil file to the grid file. Maybe something was wrong during this procedure.
I noticed another function "txt2grid", being able to create grid.bin file specifically (e.g. single grid cell or regional area). The source file (https://github.com/PIK-LPJmL/LPJmL/blob/master/src/utils/txt2grid.c) provided the text file format:
Id,Lon,Lat,X_CRU,Y_CRU
1,-179.75,-16.25,1,148 
2,.. 
If I selected some Lon Lat values, how to prepare the X_CRU and Y_CRU?
